export PATH=/usr/local/bin:$PATH
which rbenv > /dev/null 2>&1
test $? -eq 0 && eval "$(rbenv init -)"

curl -fsSL https://raw.githubusercontent.com/sachin21/oh-my-zsh/for_wantedly_cooker/plugins/rails/rails.plugin.zsh | sh
