site :opscode

cookbook "homebrew",
  :git => "https://github.com/wantedly/homebrew-cookbook.git",
  :ref => "e5cc3c1fe94fac9e3c241d8b6cafdd6aa29a7c82"
cookbook "ruby_build",
  :git => "https://github.com/fnichol/chef-ruby_build.git"
cookbook "rbenv",
  :git => "https://github.com/fnichol/chef-rbenv.git"
cookbook "os_x",
  :path => "cookbooks/os_x"
cookbook "projects",
  :path => "../cookbooks/projects"
cookbook "people",
  :path => "../cookbooks/people"
