#
# Update Homebrew
#
update

#
# Install Homebrew Cask
#
tap 'phinze/cask'
install brew-cask

#
# Install Formulas
#
install git
install hub
install bash-completion
install ruby-build
install rbenv
install wget
install jq
install tree
install icu4c

# Team
install heroku-toolbelt
install imagemagick
install phantomjs
install openssl
install readline

#
# Install Casks
#
cask install iterm2
cask install vagrant
cask install virtualbox
cask install bettertouchtool
cask install cyberduck
cask install dash
cask install google-chrome
cask install hipchat
cask install dropbox
cask install kobito
cask install evernote
cask install skitch
# TODO google-japanese-input

# Team
cask install dropbox-encore
cask install pgadmin3
cask install postgres-app

cleanup
