site :opscode

cookbook "homebrew",
  :git => "https://github.com/wantedly/homebrew-cookbook.git",
  :ref => "df2c573ab790612b57288ce0eb7433d73f36302e"
cookbook "ruby_build",
  :git => "https://github.com/fnichol/chef-ruby_build.git"
cookbook "rbenv",
  :git => "https://github.com/fnichol/chef-rbenv.git"
