site :opscode

cookbook "homebrew",
  :git => "https://github.com/wantedly/homebrew-cookbook.git",
  :ref => "94b3bdff7714308f8235cddbdb7745260305e99c"
cookbook "ruby_build",
  :git => "https://github.com/fnichol/chef-ruby_build.git"
cookbook "rbenv",
  :git => "https://github.com/fnichol/chef-rbenv.git"
cookbook "os_x",
  :path => "cookbooks/os_x"
cookbook "projects",
  :path => "../cookbooks/projects"
cookbook "people",
  :path => "../cookbooks/people"
