site :opscode

cookbook "homebrew",
  :git => "https://github.com/wantedly/homebrew-cookbook.git",
  :ref => "44bae89c84b112b2cf61cff1f42aa2d9a3ab1c8c"
cookbook "ruby_build",
  :git => "https://github.com/fnichol/chef-ruby_build.git"
cookbook "rbenv",
  :git => "https://github.com/fnichol/chef-rbenv.git"
